### ISSUE TITLE
utils - Error

### ISSUE THREAD

**Issue by FishermanJ** [CT83/SmoothStream#2]
When I try to run Streamer.py I get error. Cannot import name "is_raspberry_pi". I tried install utils but it didnt help at all.. Can you help me please?

Andrej

**Comment by CT83** [comment]
Well, I just tried to run it locally. I used two separate terminals.


* Start the viewer, on your machine, in a terminal.
```
python StreamViewer.py
```

*  Start the streamer server in a new terminal 
```
python Streamer.py -s 192.168.1.X
```
